<?php

/**
 * Implements hook_menu().
 */
function fs_search_event_menu() {
  $file_path = drupal_get_path('module', 'fs_search_event');
  $items = [];
  $cities = _fs_city_get_cities();
  foreach ($cities as $city) {
    $items[$city . '/event'] = [
      'title' => 'Event list',
      'page callback' => 'fs_search_event_list_page',
      'page arguments' => [0],
      'access callback' => TRUE,
      'file' => 'fs_search_event.pages.inc',
      'file path' => $file_path,
    ];
  }
  $items['event/autocomplete/%'] = [
    'page callback' => 'fs_search_event_autocomplete',
    'page arguments' => [2],
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'fs_search_event.pages.inc',
    'file_path' => $file_path,
  ];

  return $items;
}

/**
 * Implements hook_theme().
 */
function fs_search_event_theme() {
  $module_path = drupal_get_path('module', 'fs_search_event');

  return [
    'fs_search_event_list_page' => [
      'variables' => ['items' => NULL, 'pager' => NULL],
      'template' => 'fs_search_event_list_page',
      'path' => $module_path . '/templates',
    ],
    'fs_search_event_event_list_view' => [
      'variables' => ['item' => NULL],
      'template' => 'fs_search_event_event_list_view',
      'path' => $module_path . '/templates',
    ],
  ];
}