<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class StoreComment extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'level' => 'required|integer|in:1,2',
            'openid' => 'required',
            'nick_name' => "required",
            'head_url' => 'required',
            'bbs_id' => 'required|integer',
            'comment_id' => 'nullable',
            'content' => 'required',
            'expert' => 'required'
        ];
    }


    public function messages()
    {
        return [
        ]; // TODO: Change the autogenerated stub
    }
}
