<?php

/**
 * Implements hook_menu().
 */
function fs_gallery_menu() {
  $file_path = drupal_get_path('module', 'fs_gallery');
  $items = [];

  $cities = _fs_city_get_cities();
  foreach ($cities as $city) {
    $items[$city . '/gallery'] = [
      'title' => 'Gallery list',
      'page callback' => 'fs_gallery_list_page',
      'page arguments' => [0],
      'access callback' => TRUE,
      'file' => 'fs_gallery.pages.inc',
      'file_path' => $file_path,
    ];
  }

  return $items;
}


/**
 * Implements hook_theme().
 */
function fs_gallery_theme() {
  $module_path = drupal_get_path('module', 'fs_gallery');

  return [
    'fs_gallery_ds_default' => [
      'variables' => ['item' => NULL],
      'template' => 'fs_gallery_ds_default',
      'path' => $module_path . '/templates',
    ],
    'fs_home_gallery' => [
      'variables' => ['items' => NULL],
      'template' => 'fs_home_gallery',
      'path' => $module_path . '/templates',
    ],
    'fs_gallery_list_page' => [
      'variables' => ['items' => NULL, 'pager' => NULL],
      'template' => 'fs_gallery_list_page',
      'path' => $module_path . '/templates',
    ],
  ];
}

/**
 * Implements hook_block_info().
 */
function fs_gallery_block_info() {
  $blocks = [];

  $blocks['fs_home_gallery'] = [
    'info' => t('FS Home Gallery'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  ];

  return $blocks;
}


/**
 * Implements hook_block_view().
 */
function fs_gallery_block_view($delta = '') {
  $block = [];
  
  switch ($delta) {
    case 'fs_home_gallery':
      $block['subject'] = t('Home Gallery');

      $query = "SELECT DISTINCT(n.nid) FROM {node} AS n
                LEFT JOIN {users_roles} AS ur ON ur.uid = n.uid 
                LEFT JOIN {field_data_field_related_school} AS rs ON rs.entity_id = n.nid
                WHERE ur.rid IN ('3','4') AND n.type = 'gallery' AND n.status = 1 
                AND rs.field_related_school_target_id IS NULL
                ORDER BY n.created DESC
                LIMIT 9";

      $result = db_query($query);

      $nids = $result->fetchCol();

      $nodes = node_load_multiple($nids);

      $items = [];

      if (!empty($nodes)) {
        foreach ($nodes as $node) {
          $node_wrapper = entity_metadata_wrapper('node', $node);
          $nid = $node_wrapper->getIdentifier();
          $items[$nid]['nid'] = $nid;

          $url = $node_wrapper->url->value();
          $items[$nid]['url'] = $url;

          $title = $node_wrapper->title->value();
          $field_gallery_main_image = $node_wrapper->field_gallery_main_image->value();

          $items[$nid]['title'] = $title;

          if (!empty($field_gallery_main_image)) {
            $items[$nid]['image'] = image_style_url('gallery_home_gallery', $field_gallery_main_image['uri']);
          }
          else {
            $items[$nid]['image'] = '';
          }

        }
      }

      $variables = [
        'items' => $items,
      ];

      $block['content'] = theme('fs_home_gallery', $variables);
      break;
  }

  return $block;
}

function fs_gallery_ds_default($entity) {
  
 
  $node_wrapper = entity_metadata_wrapper('node', $entity);
  // dpm($node_wrapper->getPropertyInfo());
  $item = [];

  $title = $node_wrapper->title->value();
  $item['title'] = $title;

  $field_gallery_credit = $node_wrapper->field_gallery_credit->value();
  $item['credit'] = $field_gallery_credit;

  $created = $node_wrapper->created->value();
  $item['date'] = format_date($created, 'custom', 'Y-m');

  $field_gallery_body = $node_wrapper->field_gallery_body->value();
  $item['desc'] = $field_gallery_body['value'];


  $field_gallery_album = $node_wrapper->field_gallery_album->value();
  if (!empty($field_gallery_album)) {
    foreach ($field_gallery_album as $album_item) {
      $info['image'] = image_style_url('gallery_default_album', $album_item['uri']);
      $info['alter'] = $album_item['alt'];
      $info['title'] = $album_item['title'];
      $item['images'][] = $info;
    }
  }
  else {
    $item['images'] = NULL;
  }

  // $field_article_sub_headline = $node_wrapper->field_article_sub_headline->value();
  // $item['sub_headline'] = $field_article_sub_headline;
  //
  // $field_article_tags = $node_wrapper->field_article_tags->value();
  // if (!empty($field_article_tags)) {
  //   foreach ($field_article_tags as $tag_item) {
  //     $item['tags'][] = $tag_item->name;
  //   }
  // }
  // else {
  //   $item['tags'] = NULL;
  // }
  // 
  // $field_article_body = $node_wrapper->field_article_body->value();
  // $item['body'] = $field_article_body['value'];

  $variables = [
    'item' => $item,
  ];
  return theme('fs_gallery_ds_default', $variables);
}


/**
 * Implements hook_node_insert().
 */
function fs_gallery_node_insert($node) {
  if (isset($node->type)&&$node->type == "gallery") {
     generate_image_gallery($node);
     entity_get_controller('node')->resetCache(array($node->nid));
  }
}

/**
 * Implements hook_node_update().
 */
function fs_gallery_node_update($node) {
  if (isset($node->type)&&$node->type == "gallery") {
     generate_image_gallery($node);
     entity_get_controller('node')->resetCache(array($node->nid));
  }

}
function generate_image_gallery($node) {
  module_load_include('inc', 'fs_base', 'fs_base');
  $uri = $node->field_gallery_main_image["und"][0]["uri"];
  
  $styles = array('fs_school_video_gallery');
  try {
    foreach ($styles as $key => $value) {
       fs_base_generate_image($value,$uri);
   }
  }
  catch (Exception $e) {
   // echo 'Caught exception: ', $e->getMessage(), "\n";
  }
}

function fs_gallery_query_is_related_school_null_alter($query){
     $query->leftJoin('field_data_field_related_school', 'related_school', 'related_school.entity_id = node.nid');
     $query->isNull('related_school.field_related_school_target_id');
}